/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao;

import br.com.controle.LavarCarro;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Henrique
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jTvalor = new javax.swing.JTextField();
        jTtipo = new javax.swing.JTextField();
        jTnota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLtotalValor = new javax.swing.JLabel();
        jLmediaValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtabela = new javax.swing.JTable();
        jBcadastrar = new javax.swing.JButton();
        jBapagar = new javax.swing.JButton();
        jLtotalNota = new javax.swing.JLabel();
        jLmediaNota = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lava Jato");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo de Lavagem");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tipo de Lavagem");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor de Serviço");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nota de Serviço");

        jTcodigo.setColumns(15);

        jTvalor.setColumns(15);

        jTtipo.setColumns(15);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Media");

        jLtotalValor.setBackground(new java.awt.Color(255, 255, 255));
        jLtotalValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLtotalValor.setForeground(new java.awt.Color(255, 255, 255));

        jLmediaValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLmediaValor.setForeground(new java.awt.Color(255, 255, 255));

        jTtabela.setBackground(new java.awt.Color(250, 255, 127));
        jTtabela.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTtabela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo da Linguagem", "Tipo da Lavagem", "Valor do Serviço", "Nota do Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtabela.setGridColor(new java.awt.Color(153, 153, 153));
        jTtabela.setSelectionBackground(new java.awt.Color(233, 25, 15));
        jScrollPane1.setViewportView(jTtabela);
        if (jTtabela.getColumnModel().getColumnCount() > 0) {
            jTtabela.getColumnModel().getColumn(0).setResizable(false);
            jTtabela.getColumnModel().getColumn(1).setResizable(false);
            jTtabela.getColumnModel().getColumn(2).setResizable(false);
            jTtabela.getColumnModel().getColumn(3).setResizable(false);
        }

        jBcadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarActionPerformed(evt);
            }
        });

        jBapagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBapagar.setText("Apagar");
        jBapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBapagarActionPerformed(evt);
            }
        });

        jLtotalNota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLtotalNota.setForeground(new java.awt.Color(255, 255, 255));

        jLmediaNota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLmediaNota.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jTcodigo)
                            .addComponent(jTtipo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTnota, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTvalor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLtotalValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(jLtotalNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLmediaValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLmediaNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jBapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTnota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLmediaValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLtotalValor, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLmediaNota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLtotalNota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTnota, jTtipo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBapagar, jBcadastrar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarActionPerformed
        // Codigo Do Botao Cadastrar:

        LavarCarro lavarCarro = new LavarCarro();
        DefaultTableModel tabela = (DefaultTableModel) jTtabela.getModel();
        DecimalFormat dinheiro = new DecimalFormat(); //Classe Para Exibir Dinheiro
        dinheiro.applyPattern("R$ #,##0.00"); //Edita o Formato

        if (jTcodigo.getText().isEmpty() || jTtipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos");
        } else if (jTvalor.getText().isEmpty() || jTnota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos");
        } else if (!jTtipo.getText().matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Campo Tipo de Lavagem Preencha Somente Com Letras");
        } else if (jTcodigo.getText().matches("[a-zA-Z]*")) {
            JOptionPane.showMessageDialog(null, "Campo Codigo Preencha Somente Com Numeros");
        } else if (jTvalor.getText().matches("[a-zA-Z]*")) {
            JOptionPane.showMessageDialog(null, "Campo Valor Preencha Somente Com Numeros");
        } else if (jTnota.getText().matches("[a-zA-Z]*")) {
            JOptionPane.showMessageDialog(null, "Campo Nota Preencha Somente Com Numeros");
        } else {

            lavarCarro.setCodigoLavagem(Integer.parseInt(jTcodigo.getText()));
            lavarCarro.setTipoLavagem(jTtipo.getText());
            lavarCarro.setValorServico(Double.valueOf(jTvalor.getText()));
            lavarCarro.setNotaServico(Double.valueOf(jTnota.getText()));

            int codigo = lavarCarro.getCodigoLavagem();
            String tipo = lavarCarro.getTipoLavagem();
            Double valor = lavarCarro.getValorServico();
            Double nota = lavarCarro.getNotaServico();

            tabela.addRow(new Object[]{codigo, tipo, valor, nota}); //Colunas da Tabela

            int qtdLinhas = tabela.getRowCount(); //Quantidade de Linhas

            double totalValor = 0.0;
            double totalNota = 0.0;
            double mediaValor = 0.0;
            double mediaNota = 0.0;

            for (int i = 0; i < qtdLinhas; i++) {
                double valor1 = Double.valueOf(jTtabela.getValueAt(i, 2).toString());
                double valor2 = Double.valueOf(jTtabela.getValueAt(i, 3).toString());
                totalValor = totalValor + valor1;
                totalNota = totalNota + valor2;
                mediaValor = totalValor / qtdLinhas;
                mediaNota = totalNota / qtdLinhas;
            }

            jLtotalValor.setText("Total Valor: " + dinheiro.format(Double.valueOf(totalValor)));
            jLtotalNota.setText("Total Nota: " + totalNota);
            jLmediaValor.setText("Media Valor: " + dinheiro.format(Double.valueOf(mediaValor)));
            jLmediaNota.setText("Media Nota:  " + mediaNota);

            //Limpar os Campos de Digitação
            jTcodigo.setText("");
            jTtipo.setText("");
            jTvalor.setText("");
            jTnota.setText("");
        }

    }//GEN-LAST:event_jBcadastrarActionPerformed

    private void jBapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBapagarActionPerformed
        // Codigo do Botao de Apagar:

        if (jTtabela.getSelectedRow() == - 1) {

            JOptionPane.showMessageDialog(null, "Selecione Alguma Linha Para Excluir");

        } else {

            DefaultTableModel tabela = (DefaultTableModel) jTtabela.getModel();
            //Apagar a Linha Selecionada
            ((DefaultTableModel) jTtabela.getModel()).removeRow(jTtabela.getSelectedRow());
            DecimalFormat dinheiro = new DecimalFormat(); //Classe Para Exibir Dinheiro
            dinheiro.applyPattern("R$ #,##0.00"); //Edita o Formato

            int qtdLinhas = tabela.getRowCount(); //Quantidade de Linhas

            double totalValor = 0.0;
            double totalNota = 0.0;
            double mediaValor = 0.0;
            double mediaNota = 0.0;
            for (int i = 0; i < qtdLinhas; i++) {
                double valor1 = Double.valueOf(jTtabela.getValueAt(i, 2).toString());
                double valor2 = Double.valueOf(jTtabela.getValueAt(i, 3).toString());
                totalValor = totalValor + valor1;
                totalNota = totalNota + valor2;
                mediaValor = totalValor / qtdLinhas;
                mediaNota = totalNota / qtdLinhas;
            }

            jLtotalValor.setText("Total Valor: " + dinheiro.format(Double.valueOf(totalValor)));
            jLtotalNota.setText("Total Nota: " + totalNota);
            jLmediaValor.setText("Media Valor: " + dinheiro.format(Double.valueOf(mediaValor)));
            jLmediaNota.setText("Media Nota: " + mediaNota);;

            //Limpar os Campos de Digitação
            jTcodigo.setText("");
            jTtipo.setText("");
            jTvalor.setText("");
            jTnota.setText("");

        }


    }//GEN-LAST:event_jBapagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBapagar;
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLmediaNota;
    private javax.swing.JLabel jLmediaValor;
    private javax.swing.JLabel jLtotalNota;
    private javax.swing.JLabel jLtotalValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTnota;
    private javax.swing.JTable jTtabela;
    private javax.swing.JTextField jTtipo;
    private javax.swing.JTextField jTvalor;
    // End of variables declaration//GEN-END:variables
}
